# Generación de horarios para actividades

In [1]:
import pandas as pd
from faker import Faker
import random
import datetime

Faker.seed(42)
fake = Faker('es_MX')
random.seed(42)

df_actividades = pd.read_csv('actividades.csv')
df_actividades.iloc[0].index

Index(['destino_id', 'direccion_id', 'nombre', 'descripcion', 'precio',
       'categoria', 'id', 'tipo'],
      dtype='object')

In [2]:
df_actividades_recurrentes = df_actividades[df_actividades['tipo'] == 'recurrente']
df_actividades_eventuales = df_actividades[df_actividades['tipo'] == 'eventual']

In [3]:
df_actividades_recurrentes

,destino_id,direccion_id,nombre,descripcion,precio,categoria,id,tipo
0,2,100134,Cultural optio,Totam a similique quas. Laudantium unde velit ...,1097.72,Cultural,135,recurrente
1,33,103387,Recreativa eius,Molestiae quo modi laborum. Explicabo eligendi...,192.67,Recreativa,3388,recurrente
2,134,113406,Taller ex,Consequatur fuga magnam dolor velit sint animi...,3110.25,Taller,13407,recurrente
3,55,105477,Recreativa consequatur,Omnis minus consectetur nesciunt nulla ipsam p...,2756.58,Recreativa,5478,recurrente
4,202,120177,Gastronomía voluptas,Adipisci sint minima distinctio eligendi. Quia...,4040.76,Gastronomía,20178,recurrente
...,...,...,...,...,...,...,...,...
17951,33,103359,Tour hic,Illum eaque fugiat sit maiores. Sequi veritati...,4157.40,Tour,3360,recurrente
17952,3,100307,Concierto minus,Doloremque hic corrupti necessitatibus rem fac...,1061.89,Concierto,308,recurrente
17953,225,122320,Visita Guiada assumenda,Eos nesciunt iste distinctio.,2134.74,Visita Guiada,22321,recurrente
17954,192,119162,Playa eaque,Odit corporis quia ratione est.,1040.78,Playa,19163,recurrente
17955,126,112580,Tour distinctio,Repellat enim expedita facere nam repudiandae ...,1610.24,Tour,12581,recurrente

In [4]:
df_actividades_eventuales

,destino_id,direccion_id,nombre,descripcion,precio,categoria,id,tipo
17956,1,100009,Concierto incidunt,Inventore neque omnis iure ipsam. Maiores recu...,3161.77,Concierto,10,eventual
17957,1,100011,Educativa facere,Non vitae quaerat quod. Vitae autem ad est. Id...,4283.82,Educativa,12,eventual
17958,1,100013,Cultural nemo,Recusandae nisi repudiandae ullam. Commodi por...,1371.54,Cultural,14,eventual
17959,1,100016,Mercado numquam,Temporibus aliquid recusandae eos fugiat. Dolo...,3853.15,Mercado,17,eventual
17960,1,100024,Cultural incidunt,Dolores odit numquam. Beatae temporibus nisi a...,364.46,Cultural,25,eventual
...,...,...,...,...,...,...,...,...
22440,225,122427,Deportiva sunt,Dolor cumque natus. Fugit quod alias repellendus.,4750.45,Deportiva,22428,eventual
22441,225,122428,Feria esse,Eius facere laudantium officia repudiandae qui...,1955.96,Feria,22429,eventual
22442,225,122435,Recreativa iusto,Molestiae sequi autem explicabo. Sunt dignissi...,1407.61,Recreativa,22436,eventual
22443,225,122442,Playa autem,Inventore molestias doloremque officia ab.,657.18,Playa,22443,eventual
22444,225,122444,Playa dolorum,Reiciendis facilis ipsum veritatis labore. Pos...,2442.09,Playa,22445,eventual

## Horarios recurrentes

In [5]:
horarios_recurrentes = list()

cant_dias_por_semana = [5,6,7]
horas_inicio = [
    '07:00',
    '08:00',
    '09:00',
    '10:00',
    '11:00',
    '12:00',
    '13:00',
    '14:00',
    '15:00',
    '16:00',
    '17:00',
    '18:00',
    '19:00',
    '20:00',
    '21:00',
    '22:00',
    '23:00',
]

def generar_horario_recurrente(actividad_id, dia, hora_inicio):
    horario = dict()
    horario['actividad_id'] = actividad_id
    horario['dia_semana'] = dia
    horario['hora_inicio'] = horas_inicio[hora_inicio]
    # Sábado o Domingo cierra más temprano
    if (dia == 5 or dia == 6):
        horario['hora_fin'] = horas_inicio[hora_inicio+6]
    else:
        horario['hora_fin'] = horas_inicio[hora_inicio+8]

    horarios_recurrentes.append(horario)

def generar_horarios_recurrente(actividad):
    dias_semana = random.choice(cant_dias_por_semana)
    for dia in range(dias_semana):
        hora_inicio = random.randint(0, 6)
        generar_horario_recurrente(actividad.id, dia, hora_inicio)

In [6]:
df_actividades_recurrentes.apply(generar_horarios_recurrente, axis=1)

0        None
1        None
2        None
3        None
4        None
         ...
17951    None
17952    None
17953    None
17954    None
17955    None
Length: 17956, dtype: object

In [7]:
df_horarios_recurrentes = pd.DataFrame(horarios_recurrentes)

## Horarios eventuales

In [8]:
horarios_eventuales = list()

horas_inicio = [
    '07:00',
    '08:00',
    '09:00',
    '10:00',
    '11:00',
    '12:00',
    '13:00',
    '14:00',
    '15:00',
    '16:00',
    '17:00',
    '18:00',
    '19:00',
    '20:00',
    '21:00',
    '22:00',
    '23:00',
]


def generar_horario_eventual(actividad_id, dia, hora_inicio):
    horario = dict()
    horario['actividad_id'] = actividad_id
    horario['fecha'] = dia.strftime("%Y-%m-%d")
    horario['hora_inicio'] = horas_inicio[hora_inicio]
    # Sábado o Domingo cierra más temprano
    horario['hora_fin'] = horas_inicio[hora_inicio+random.randint(2, 6)]

    horarios_eventuales.append(horario)

def generar_horarios_eventuales(actividad):
    dias_duracion = random.randint(1, 7)
    dia_inicio = fake.date_between('+1w', datetime.date(2026, 1, 1))
    hora_inicio = random.randint(0, 6)
    for i in range(dias_duracion):
        dia = dia_inicio + datetime.timedelta(days=i)
        generar_horario_eventual(actividad.id, dia, hora_inicio)

In [9]:
df_actividades_eventuales.apply(generar_horarios_eventuales, axis=1)
df_horarios_eventuales = pd.DataFrame(horarios_eventuales)

In [10]:
df_horarios_eventuales

       actividad_id       fecha hora_inicio hora_fin
0                10  2025-10-08       12:00    17:00
1                10  2025-10-09       12:00    14:00
2                10  2025-10-10       12:00    14:00
3                12  2025-05-16       11:00    17:00
4                12  2025-05-17       11:00    16:00
...             ...         ...         ...      ...
17715         22445  2025-07-15       09:00    11:00
17716         22445  2025-07-16       09:00    13:00
17717         22445  2025-07-17       09:00    15:00
17718         22445  2025-07-18       09:00    15:00
17719         22445  2025-07-19       09:00    11:00

[17720 rows x 4 columns]

## Exportar

In [11]:
df_horarios_recurrentes.to_csv('./horarios_recurrentes.csv', index=False)
df_horarios_eventuales.to_csv('./horarios_eventuales.csv', index=False)